/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "TempMon.h"
#include "TempMon_Run.h"
#include "unity.h"
#include "mock_TempMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TempMon_Run_NORMAL_to_OVER_TransitionAboveThreshold(void);
extern void test_TempMon_Run_NORMAL_to_UNDER_TransitionBelowThreshold(void);
extern void test_TempMon_Run_NORMAL_StaysNormalWithinThresholds(void);
extern void test_TempMon_Run_NORMAL_AtOverThresholdBoundaryStaysNormal(void);
extern void test_TempMon_Run_NORMAL_JustAboveOverThresholdTransitionsToOVER(void);
extern void test_TempMon_Run_NORMAL_AtUnderThresholdBoundaryStaysNormal(void);
extern void test_TempMon_Run_NORMAL_JustBelowUnderThresholdTransitionsToUNDER(void);
extern void test_TempMon_Run_UNDER_StaysUnderBelowThreshold(void);
extern void test_TempMon_Run_UNDER_to_NORMAL_TransitionAboveHysteresisThreshold(void);
extern void test_TempMon_Run_UNDER_AtHysteresisThresholdStaysUnder(void);
extern void test_TempMon_Run_UNDER_StaysUnderBetweenUnderAndHysteresis(void);
extern void test_TempMon_Run_OVER_StaysOverAboveThreshold(void);
extern void test_TempMon_Run_OVER_to_NORMAL_TransitionBelowHysteresisThreshold(void);
extern void test_TempMon_Run_OVER_AtHysteresisThresholdStaysOver(void);
extern void test_TempMon_Run_OVER_StaysOverBetweenOverAndHysteresis(void);
extern void test_TempMon_Run_HysteresisPreventOscillationAtUnderThreshold(void);
extern void test_TempMon_Run_HysteresisPreventOscillationAtOverThreshold(void);
extern void test_TempMon_Run_SequentialTransitions_NORMAL_OVER_NORMAL(void);
extern void test_TempMon_Run_SequentialTransitions_NORMAL_UNDER_NORMAL(void);
extern void test_TempMon_Run_MultipleCyclesNormalOver(void);
extern void test_TempMon_Run_CustomThresholdAndHysteresis(void);
extern void test_TempMon_Run_ExtremeTemperatureValues(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_TempMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_TempMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_TempMon_priv_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_TempMon_Run.c");
  run_test(test_TempMon_Run_NORMAL_to_OVER_TransitionAboveThreshold, "test_TempMon_Run_NORMAL_to_OVER_TransitionAboveThreshold", 30);
  run_test(test_TempMon_Run_NORMAL_to_UNDER_TransitionBelowThreshold, "test_TempMon_Run_NORMAL_to_UNDER_TransitionBelowThreshold", 43);
  run_test(test_TempMon_Run_NORMAL_StaysNormalWithinThresholds, "test_TempMon_Run_NORMAL_StaysNormalWithinThresholds", 55);
  run_test(test_TempMon_Run_NORMAL_AtOverThresholdBoundaryStaysNormal, "test_TempMon_Run_NORMAL_AtOverThresholdBoundaryStaysNormal", 68);
  run_test(test_TempMon_Run_NORMAL_JustAboveOverThresholdTransitionsToOVER, "test_TempMon_Run_NORMAL_JustAboveOverThresholdTransitionsToOVER", 81);
  run_test(test_TempMon_Run_NORMAL_AtUnderThresholdBoundaryStaysNormal, "test_TempMon_Run_NORMAL_AtUnderThresholdBoundaryStaysNormal", 94);
  run_test(test_TempMon_Run_NORMAL_JustBelowUnderThresholdTransitionsToUNDER, "test_TempMon_Run_NORMAL_JustBelowUnderThresholdTransitionsToUNDER", 107);
  run_test(test_TempMon_Run_UNDER_StaysUnderBelowThreshold, "test_TempMon_Run_UNDER_StaysUnderBelowThreshold", 121);
  run_test(test_TempMon_Run_UNDER_to_NORMAL_TransitionAboveHysteresisThreshold, "test_TempMon_Run_UNDER_to_NORMAL_TransitionAboveHysteresisThreshold", 134);
  run_test(test_TempMon_Run_UNDER_AtHysteresisThresholdStaysUnder, "test_TempMon_Run_UNDER_AtHysteresisThresholdStaysUnder", 147);
  run_test(test_TempMon_Run_UNDER_StaysUnderBetweenUnderAndHysteresis, "test_TempMon_Run_UNDER_StaysUnderBetweenUnderAndHysteresis", 161);
  run_test(test_TempMon_Run_OVER_StaysOverAboveThreshold, "test_TempMon_Run_OVER_StaysOverAboveThreshold", 176);
  run_test(test_TempMon_Run_OVER_to_NORMAL_TransitionBelowHysteresisThreshold, "test_TempMon_Run_OVER_to_NORMAL_TransitionBelowHysteresisThreshold", 189);
  run_test(test_TempMon_Run_OVER_AtHysteresisThresholdStaysOver, "test_TempMon_Run_OVER_AtHysteresisThresholdStaysOver", 202);
  run_test(test_TempMon_Run_OVER_StaysOverBetweenOverAndHysteresis, "test_TempMon_Run_OVER_StaysOverBetweenOverAndHysteresis", 216);
  run_test(test_TempMon_Run_HysteresisPreventOscillationAtUnderThreshold, "test_TempMon_Run_HysteresisPreventOscillationAtUnderThreshold", 230);
  run_test(test_TempMon_Run_HysteresisPreventOscillationAtOverThreshold, "test_TempMon_Run_HysteresisPreventOscillationAtOverThreshold", 245);
  run_test(test_TempMon_Run_SequentialTransitions_NORMAL_OVER_NORMAL, "test_TempMon_Run_SequentialTransitions_NORMAL_OVER_NORMAL", 263);
  run_test(test_TempMon_Run_SequentialTransitions_NORMAL_UNDER_NORMAL, "test_TempMon_Run_SequentialTransitions_NORMAL_UNDER_NORMAL", 282);
  run_test(test_TempMon_Run_MultipleCyclesNormalOver, "test_TempMon_Run_MultipleCyclesNormalOver", 301);
  run_test(test_TempMon_Run_CustomThresholdAndHysteresis, "test_TempMon_Run_CustomThresholdAndHysteresis", 318);
  run_test(test_TempMon_Run_ExtremeTemperatureValues, "test_TempMon_Run_ExtremeTemperatureValues", 342);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
