/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TEMPMON_H
#define _MOCK_TEMPMON_H

#include "unity.h"
#include "TempMon.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_TempMon_Init(void);
void mock_TempMon_Destroy(void);
void mock_TempMon_Verify(void);




#define TempMon_Init_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("TempMon_Init requires _Ignore (not AndReturn)");
#define TempMon_Init_Ignore() TempMon_Init_CMockIgnore()
void TempMon_Init_CMockIgnore(void);
#define TempMon_Init_StopIgnore() TempMon_Init_CMockStopIgnore()
void TempMon_Init_CMockStopIgnore(void);
#define TempMon_Init_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("TempMon_Init requires _ExpectAnyArgs (not AndReturn)");
#define TempMon_Init_ExpectAnyArgs() TempMon_Init_CMockExpectAnyArgs(__LINE__)
void TempMon_Init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define TempMon_Init_ExpectAndReturn(temp_mC, cmock_retval) TEST_FAIL_MESSAGE("TempMon_Init requires _Expect (not AndReturn)");
#define TempMon_Init_Expect(temp_mC) TempMon_Init_CMockExpect(__LINE__, temp_mC)
void TempMon_Init_CMockExpect(UNITY_LINE_TYPE cmock_line, int32_t temp_mC);
typedef void (* CMOCK_TempMon_Init_CALLBACK)(int32_t temp_mC, int cmock_num_calls);
void TempMon_Init_AddCallback(CMOCK_TempMon_Init_CALLBACK Callback);
void TempMon_Init_Stub(CMOCK_TempMon_Init_CALLBACK Callback);
#define TempMon_Init_StubWithCallback TempMon_Init_Stub
#define TempMon_Init_IgnoreArg_temp_mC() TempMon_Init_CMockIgnoreArg_temp_mC(__LINE__)
void TempMon_Init_CMockIgnoreArg_temp_mC(UNITY_LINE_TYPE cmock_line);
#define TempMon_Run_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("TempMon_Run requires _Ignore (not AndReturn)");
#define TempMon_Run_Ignore() TempMon_Run_CMockIgnore()
void TempMon_Run_CMockIgnore(void);
#define TempMon_Run_StopIgnore() TempMon_Run_CMockStopIgnore()
void TempMon_Run_CMockStopIgnore(void);
#define TempMon_Run_ExpectAnyArgsAndReturn(cmock_retval) TEST_FAIL_MESSAGE("TempMon_Run requires _ExpectAnyArgs (not AndReturn)");
#define TempMon_Run_ExpectAnyArgs() TempMon_Run_CMockExpectAnyArgs(__LINE__)
void TempMon_Run_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define TempMon_Run_ExpectAndReturn(temp_mC, cmock_retval) TEST_FAIL_MESSAGE("TempMon_Run requires _Expect (not AndReturn)");
#define TempMon_Run_Expect(temp_mC) TempMon_Run_CMockExpect(__LINE__, temp_mC)
void TempMon_Run_CMockExpect(UNITY_LINE_TYPE cmock_line, int32_t temp_mC);
typedef void (* CMOCK_TempMon_Run_CALLBACK)(int32_t temp_mC, int cmock_num_calls);
void TempMon_Run_AddCallback(CMOCK_TempMon_Run_CALLBACK Callback);
void TempMon_Run_Stub(CMOCK_TempMon_Run_CALLBACK Callback);
#define TempMon_Run_StubWithCallback TempMon_Run_Stub
#define TempMon_Run_IgnoreArg_temp_mC() TempMon_Run_CMockIgnoreArg_temp_mC(__LINE__)
void TempMon_Run_CMockIgnoreArg_temp_mC(UNITY_LINE_TYPE cmock_line);
#define TempMon_GetSts_Ignore() TEST_FAIL_MESSAGE("TempMon_GetSts requires _IgnoreAndReturn");
#define TempMon_GetSts_IgnoreAndReturn(cmock_retval) TempMon_GetSts_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void TempMon_GetSts_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TempMon_sts_e cmock_to_return);
#define TempMon_GetSts_StopIgnore() TempMon_GetSts_CMockStopIgnore()
void TempMon_GetSts_CMockStopIgnore(void);
#define TempMon_GetSts_Expect() TEST_FAIL_MESSAGE("TempMon_GetSts requires _ExpectAndReturn");
#define TempMon_GetSts_ExpectAndReturn(cmock_retval) TempMon_GetSts_CMockExpectAndReturn(__LINE__, cmock_retval)
void TempMon_GetSts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TempMon_sts_e cmock_to_return);
typedef TempMon_sts_e (* CMOCK_TempMon_GetSts_CALLBACK)(int cmock_num_calls);
void TempMon_GetSts_AddCallback(CMOCK_TempMon_GetSts_CALLBACK Callback);
void TempMon_GetSts_Stub(CMOCK_TempMon_GetSts_CALLBACK Callback);
#define TempMon_GetSts_StubWithCallback TempMon_GetSts_Stub
#define TempMon_IsOverAlv_b_Ignore() TEST_FAIL_MESSAGE("TempMon_IsOverAlv_b requires _IgnoreAndReturn");
#define TempMon_IsOverAlv_b_IgnoreAndReturn(cmock_retval) TempMon_IsOverAlv_b_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void TempMon_IsOverAlv_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return);
#define TempMon_IsOverAlv_b_StopIgnore() TempMon_IsOverAlv_b_CMockStopIgnore()
void TempMon_IsOverAlv_b_CMockStopIgnore(void);
#define TempMon_IsOverAlv_b_Expect() TEST_FAIL_MESSAGE("TempMon_IsOverAlv_b requires _ExpectAndReturn");
#define TempMon_IsOverAlv_b_ExpectAndReturn(cmock_retval) TempMon_IsOverAlv_b_CMockExpectAndReturn(__LINE__, cmock_retval)
void TempMon_IsOverAlv_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return);
typedef _Bool (* CMOCK_TempMon_IsOverAlv_b_CALLBACK)(int cmock_num_calls);
void TempMon_IsOverAlv_b_AddCallback(CMOCK_TempMon_IsOverAlv_b_CALLBACK Callback);
void TempMon_IsOverAlv_b_Stub(CMOCK_TempMon_IsOverAlv_b_CALLBACK Callback);
#define TempMon_IsOverAlv_b_StubWithCallback TempMon_IsOverAlv_b_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
