/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_TEMPMON_PRIV_H
#define _MOCK_TEMPMON_PRIV_H

#include "TempMon_priv.h"
#include "unity.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 ||                                                            \
    (__GNUC__ == 4 &&                                                          \
     (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_TempMon_priv_Init(void);
void mock_TempMon_priv_Destroy(void);
void mock_TempMon_priv_Verify(void);

#define IsUnderEnter_b_Ignore()                                                \
  TEST_FAIL_MESSAGE("IsUnderEnter_b requires _IgnoreAndReturn");
#define IsUnderEnter_b_IgnoreAndReturn(cmock_retval)                           \
  IsUnderEnter_b_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IsUnderEnter_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line,
                                         _Bool cmock_to_return);
#define IsUnderEnter_b_StopIgnore() IsUnderEnter_b_CMockStopIgnore()
void IsUnderEnter_b_CMockStopIgnore(void);
#define IsUnderEnter_b_Expect(temp_mC)                                         \
  TEST_FAIL_MESSAGE("IsUnderEnter_b requires _ExpectAndReturn");
#define IsUnderEnter_b_ExpectAndReturn(temp_mC, cmock_retval)                  \
  IsUnderEnter_b_CMockExpectAndReturn(__LINE__, temp_mC, cmock_retval)
void IsUnderEnter_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line,
                                         int32_t temp_mC,
                                         _Bool cmock_to_return);
typedef _Bool (*CMOCK_IsUnderEnter_b_CALLBACK)(int32_t temp_mC,
                                               int cmock_num_calls);
void IsUnderEnter_b_AddCallback(CMOCK_IsUnderEnter_b_CALLBACK Callback);
void IsUnderEnter_b_Stub(CMOCK_IsUnderEnter_b_CALLBACK Callback);
#define IsUnderEnter_b_StubWithCallback IsUnderEnter_b_Stub
#define IsUnderExit_b_Ignore()                                                 \
  TEST_FAIL_MESSAGE("IsUnderExit_b requires _IgnoreAndReturn");
#define IsUnderExit_b_IgnoreAndReturn(cmock_retval)                            \
  IsUnderExit_b_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IsUnderExit_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line,
                                        _Bool cmock_to_return);
#define IsUnderExit_b_StopIgnore() IsUnderExit_b_CMockStopIgnore()
void IsUnderExit_b_CMockStopIgnore(void);
#define IsUnderExit_b_Expect(temp_mC)                                          \
  TEST_FAIL_MESSAGE("IsUnderExit_b requires _ExpectAndReturn");
#define IsUnderExit_b_ExpectAndReturn(temp_mC, cmock_retval)                   \
  IsUnderExit_b_CMockExpectAndReturn(__LINE__, temp_mC, cmock_retval)
void IsUnderExit_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line,
                                        int32_t temp_mC, _Bool cmock_to_return);
typedef _Bool (*CMOCK_IsUnderExit_b_CALLBACK)(int32_t temp_mC,
                                              int cmock_num_calls);
void IsUnderExit_b_AddCallback(CMOCK_IsUnderExit_b_CALLBACK Callback);
void IsUnderExit_b_Stub(CMOCK_IsUnderExit_b_CALLBACK Callback);
#define IsUnderExit_b_StubWithCallback IsUnderExit_b_Stub
#define IsOverEnter_b_Ignore()                                                 \
  TEST_FAIL_MESSAGE("IsOverEnter_b requires _IgnoreAndReturn");
#define IsOverEnter_b_IgnoreAndReturn(cmock_retval)                            \
  IsOverEnter_b_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IsOverEnter_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line,
                                        _Bool cmock_to_return);
#define IsOverEnter_b_StopIgnore() IsOverEnter_b_CMockStopIgnore()
void IsOverEnter_b_CMockStopIgnore(void);
#define IsOverEnter_b_Expect(temp_mC)                                          \
  TEST_FAIL_MESSAGE("IsOverEnter_b requires _ExpectAndReturn");
#define IsOverEnter_b_ExpectAndReturn(temp_mC, cmock_retval)                   \
  IsOverEnter_b_CMockExpectAndReturn(__LINE__, temp_mC, cmock_retval)
void IsOverEnter_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line,
                                        int32_t temp_mC, _Bool cmock_to_return);
typedef _Bool (*CMOCK_IsOverEnter_b_CALLBACK)(int32_t temp_mC,
                                              int cmock_num_calls);
void IsOverEnter_b_AddCallback(CMOCK_IsOverEnter_b_CALLBACK Callback);
void IsOverEnter_b_Stub(CMOCK_IsOverEnter_b_CALLBACK Callback);
#define IsOverEnter_b_StubWithCallback IsOverEnter_b_Stub
#define IsOverExit_b_Ignore()                                                  \
  TEST_FAIL_MESSAGE("IsOverExit_b requires _IgnoreAndReturn");
#define IsOverExit_b_IgnoreAndReturn(cmock_retval)                             \
  IsOverExit_b_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void IsOverExit_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line,
                                       _Bool cmock_to_return);
#define IsOverExit_b_StopIgnore() IsOverExit_b_CMockStopIgnore()
void IsOverExit_b_CMockStopIgnore(void);
#define IsOverExit_b_Expect(temp_mC)                                           \
  TEST_FAIL_MESSAGE("IsOverExit_b requires _ExpectAndReturn");
#define IsOverExit_b_ExpectAndReturn(temp_mC, cmock_retval)                    \
  IsOverExit_b_CMockExpectAndReturn(__LINE__, temp_mC, cmock_retval)
void IsOverExit_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line,
                                       int32_t temp_mC, _Bool cmock_to_return);
typedef _Bool (*CMOCK_IsOverExit_b_CALLBACK)(int32_t temp_mC,
                                             int cmock_num_calls);
void IsOverExit_b_AddCallback(CMOCK_IsOverExit_b_CALLBACK Callback);
void IsOverExit_b_Stub(CMOCK_IsOverExit_b_CALLBACK Callback);
#define IsOverExit_b_StubWithCallback IsOverExit_b_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 ||                                                            \
    (__GNUC__ == 4 &&                                                          \
     (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
