/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_TempMon_priv.h"

static const char* CMockString_IsOverEnter_b = "IsOverEnter_b";
static const char* CMockString_IsOverExit_b = "IsOverExit_b";
static const char* CMockString_IsUnderEnter_b = "IsUnderEnter_b";
static const char* CMockString_IsUnderExit_b = "IsUnderExit_b";
static const char* CMockString_temp_mC = "temp_mC";

typedef struct _CMOCK_IsUnderEnter_b_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  int32_t Expected_temp_mC;

} CMOCK_IsUnderEnter_b_CALL_INSTANCE;

typedef struct _CMOCK_IsUnderExit_b_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  int32_t Expected_temp_mC;

} CMOCK_IsUnderExit_b_CALL_INSTANCE;

typedef struct _CMOCK_IsOverEnter_b_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  int32_t Expected_temp_mC;

} CMOCK_IsOverEnter_b_CALL_INSTANCE;

typedef struct _CMOCK_IsOverExit_b_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  _Bool ReturnVal;
  int CallOrder;
  int32_t Expected_temp_mC;

} CMOCK_IsOverExit_b_CALL_INSTANCE;

static struct mock_TempMon_privInstance
{
  char IsUnderEnter_b_IgnoreBool;
  _Bool IsUnderEnter_b_FinalReturn;
  char IsUnderEnter_b_CallbackBool;
  CMOCK_IsUnderEnter_b_CALLBACK IsUnderEnter_b_CallbackFunctionPointer;
  int IsUnderEnter_b_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE IsUnderEnter_b_CallInstance;
  char IsUnderExit_b_IgnoreBool;
  _Bool IsUnderExit_b_FinalReturn;
  char IsUnderExit_b_CallbackBool;
  CMOCK_IsUnderExit_b_CALLBACK IsUnderExit_b_CallbackFunctionPointer;
  int IsUnderExit_b_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE IsUnderExit_b_CallInstance;
  char IsOverEnter_b_IgnoreBool;
  _Bool IsOverEnter_b_FinalReturn;
  char IsOverEnter_b_CallbackBool;
  CMOCK_IsOverEnter_b_CALLBACK IsOverEnter_b_CallbackFunctionPointer;
  int IsOverEnter_b_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE IsOverEnter_b_CallInstance;
  char IsOverExit_b_IgnoreBool;
  _Bool IsOverExit_b_FinalReturn;
  char IsOverExit_b_CallbackBool;
  CMOCK_IsOverExit_b_CALLBACK IsOverExit_b_CallbackFunctionPointer;
  int IsOverExit_b_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE IsOverExit_b_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_TempMon_priv_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.IsUnderEnter_b_CallInstance;
  if (Mock.IsUnderEnter_b_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IsUnderEnter_b);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.IsUnderEnter_b_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.IsUnderExit_b_CallInstance;
  if (Mock.IsUnderExit_b_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IsUnderExit_b);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.IsUnderExit_b_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.IsOverEnter_b_CallInstance;
  if (Mock.IsOverEnter_b_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IsOverEnter_b);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.IsOverEnter_b_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.IsOverExit_b_CallInstance;
  if (Mock.IsOverExit_b_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_IsOverExit_b);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.IsOverExit_b_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_TempMon_priv_Init(void)
{
  mock_TempMon_priv_Destroy();
}

void mock_TempMon_priv_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

_Bool IsUnderEnter_b(int32_t temp_mC)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IsUnderEnter_b_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IsUnderEnter_b);
  cmock_call_instance = (CMOCK_IsUnderEnter_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IsUnderEnter_b_CallInstance);
  Mock.IsUnderEnter_b_CallInstance = CMock_Guts_MemNext(Mock.IsUnderEnter_b_CallInstance);
  if (Mock.IsUnderEnter_b_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.IsUnderEnter_b_FinalReturn;
    memcpy((void*)(&Mock.IsUnderEnter_b_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.IsUnderEnter_b_CallbackBool &&
      Mock.IsUnderEnter_b_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.IsUnderEnter_b_CallbackFunctionPointer(temp_mC, Mock.IsUnderEnter_b_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_IsUnderEnter_b,CMockString_temp_mC);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_temp_mC, temp_mC, cmock_line, CMockStringMismatch);
  }
  if (Mock.IsUnderEnter_b_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.IsUnderEnter_b_CallbackFunctionPointer(temp_mC, Mock.IsUnderEnter_b_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IsUnderEnter_b(CMOCK_IsUnderEnter_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC);
void CMockExpectParameters_IsUnderEnter_b(CMOCK_IsUnderEnter_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC)
{
  cmock_call_instance->Expected_temp_mC = temp_mC;
}

void IsUnderEnter_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsUnderEnter_b_CALL_INSTANCE));
  CMOCK_IsUnderEnter_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsUnderEnter_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsUnderEnter_b_CallInstance = CMock_Guts_MemChain(Mock.IsUnderEnter_b_CallInstance, cmock_guts_index);
  Mock.IsUnderEnter_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.IsUnderEnter_b_IgnoreBool = (char)1;
}

void IsUnderEnter_b_CMockStopIgnore(void)
{
  if(Mock.IsUnderEnter_b_IgnoreBool)
    Mock.IsUnderEnter_b_CallInstance = CMock_Guts_MemNext(Mock.IsUnderEnter_b_CallInstance);
  Mock.IsUnderEnter_b_IgnoreBool = (char)0;
}

void IsUnderEnter_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int32_t temp_mC, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsUnderEnter_b_CALL_INSTANCE));
  CMOCK_IsUnderEnter_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsUnderEnter_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsUnderEnter_b_CallInstance = CMock_Guts_MemChain(Mock.IsUnderEnter_b_CallInstance, cmock_guts_index);
  Mock.IsUnderEnter_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_IsUnderEnter_b(cmock_call_instance, temp_mC);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void IsUnderEnter_b_AddCallback(CMOCK_IsUnderEnter_b_CALLBACK Callback)
{
  Mock.IsUnderEnter_b_IgnoreBool = (char)0;
  Mock.IsUnderEnter_b_CallbackBool = (char)1;
  Mock.IsUnderEnter_b_CallbackFunctionPointer = Callback;
}

void IsUnderEnter_b_Stub(CMOCK_IsUnderEnter_b_CALLBACK Callback)
{
  Mock.IsUnderEnter_b_IgnoreBool = (char)0;
  Mock.IsUnderEnter_b_CallbackBool = (char)0;
  Mock.IsUnderEnter_b_CallbackFunctionPointer = Callback;
}

_Bool IsUnderExit_b(int32_t temp_mC)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IsUnderExit_b_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IsUnderExit_b);
  cmock_call_instance = (CMOCK_IsUnderExit_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IsUnderExit_b_CallInstance);
  Mock.IsUnderExit_b_CallInstance = CMock_Guts_MemNext(Mock.IsUnderExit_b_CallInstance);
  if (Mock.IsUnderExit_b_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.IsUnderExit_b_FinalReturn;
    memcpy((void*)(&Mock.IsUnderExit_b_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.IsUnderExit_b_CallbackBool &&
      Mock.IsUnderExit_b_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.IsUnderExit_b_CallbackFunctionPointer(temp_mC, Mock.IsUnderExit_b_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_IsUnderExit_b,CMockString_temp_mC);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_temp_mC, temp_mC, cmock_line, CMockStringMismatch);
  }
  if (Mock.IsUnderExit_b_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.IsUnderExit_b_CallbackFunctionPointer(temp_mC, Mock.IsUnderExit_b_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IsUnderExit_b(CMOCK_IsUnderExit_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC);
void CMockExpectParameters_IsUnderExit_b(CMOCK_IsUnderExit_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC)
{
  cmock_call_instance->Expected_temp_mC = temp_mC;
}

void IsUnderExit_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsUnderExit_b_CALL_INSTANCE));
  CMOCK_IsUnderExit_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsUnderExit_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsUnderExit_b_CallInstance = CMock_Guts_MemChain(Mock.IsUnderExit_b_CallInstance, cmock_guts_index);
  Mock.IsUnderExit_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.IsUnderExit_b_IgnoreBool = (char)1;
}

void IsUnderExit_b_CMockStopIgnore(void)
{
  if(Mock.IsUnderExit_b_IgnoreBool)
    Mock.IsUnderExit_b_CallInstance = CMock_Guts_MemNext(Mock.IsUnderExit_b_CallInstance);
  Mock.IsUnderExit_b_IgnoreBool = (char)0;
}

void IsUnderExit_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int32_t temp_mC, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsUnderExit_b_CALL_INSTANCE));
  CMOCK_IsUnderExit_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsUnderExit_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsUnderExit_b_CallInstance = CMock_Guts_MemChain(Mock.IsUnderExit_b_CallInstance, cmock_guts_index);
  Mock.IsUnderExit_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_IsUnderExit_b(cmock_call_instance, temp_mC);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void IsUnderExit_b_AddCallback(CMOCK_IsUnderExit_b_CALLBACK Callback)
{
  Mock.IsUnderExit_b_IgnoreBool = (char)0;
  Mock.IsUnderExit_b_CallbackBool = (char)1;
  Mock.IsUnderExit_b_CallbackFunctionPointer = Callback;
}

void IsUnderExit_b_Stub(CMOCK_IsUnderExit_b_CALLBACK Callback)
{
  Mock.IsUnderExit_b_IgnoreBool = (char)0;
  Mock.IsUnderExit_b_CallbackBool = (char)0;
  Mock.IsUnderExit_b_CallbackFunctionPointer = Callback;
}

_Bool IsOverEnter_b(int32_t temp_mC)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IsOverEnter_b_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IsOverEnter_b);
  cmock_call_instance = (CMOCK_IsOverEnter_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IsOverEnter_b_CallInstance);
  Mock.IsOverEnter_b_CallInstance = CMock_Guts_MemNext(Mock.IsOverEnter_b_CallInstance);
  if (Mock.IsOverEnter_b_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.IsOverEnter_b_FinalReturn;
    memcpy((void*)(&Mock.IsOverEnter_b_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.IsOverEnter_b_CallbackBool &&
      Mock.IsOverEnter_b_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.IsOverEnter_b_CallbackFunctionPointer(temp_mC, Mock.IsOverEnter_b_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_IsOverEnter_b,CMockString_temp_mC);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_temp_mC, temp_mC, cmock_line, CMockStringMismatch);
  }
  if (Mock.IsOverEnter_b_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.IsOverEnter_b_CallbackFunctionPointer(temp_mC, Mock.IsOverEnter_b_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IsOverEnter_b(CMOCK_IsOverEnter_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC);
void CMockExpectParameters_IsOverEnter_b(CMOCK_IsOverEnter_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC)
{
  cmock_call_instance->Expected_temp_mC = temp_mC;
}

void IsOverEnter_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsOverEnter_b_CALL_INSTANCE));
  CMOCK_IsOverEnter_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsOverEnter_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsOverEnter_b_CallInstance = CMock_Guts_MemChain(Mock.IsOverEnter_b_CallInstance, cmock_guts_index);
  Mock.IsOverEnter_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.IsOverEnter_b_IgnoreBool = (char)1;
}

void IsOverEnter_b_CMockStopIgnore(void)
{
  if(Mock.IsOverEnter_b_IgnoreBool)
    Mock.IsOverEnter_b_CallInstance = CMock_Guts_MemNext(Mock.IsOverEnter_b_CallInstance);
  Mock.IsOverEnter_b_IgnoreBool = (char)0;
}

void IsOverEnter_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int32_t temp_mC, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsOverEnter_b_CALL_INSTANCE));
  CMOCK_IsOverEnter_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsOverEnter_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsOverEnter_b_CallInstance = CMock_Guts_MemChain(Mock.IsOverEnter_b_CallInstance, cmock_guts_index);
  Mock.IsOverEnter_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_IsOverEnter_b(cmock_call_instance, temp_mC);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void IsOverEnter_b_AddCallback(CMOCK_IsOverEnter_b_CALLBACK Callback)
{
  Mock.IsOverEnter_b_IgnoreBool = (char)0;
  Mock.IsOverEnter_b_CallbackBool = (char)1;
  Mock.IsOverEnter_b_CallbackFunctionPointer = Callback;
}

void IsOverEnter_b_Stub(CMOCK_IsOverEnter_b_CALLBACK Callback)
{
  Mock.IsOverEnter_b_IgnoreBool = (char)0;
  Mock.IsOverEnter_b_CallbackBool = (char)0;
  Mock.IsOverEnter_b_CallbackFunctionPointer = Callback;
}

_Bool IsOverExit_b(int32_t temp_mC)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_IsOverExit_b_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_IsOverExit_b);
  cmock_call_instance = (CMOCK_IsOverExit_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.IsOverExit_b_CallInstance);
  Mock.IsOverExit_b_CallInstance = CMock_Guts_MemNext(Mock.IsOverExit_b_CallInstance);
  if (Mock.IsOverExit_b_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.IsOverExit_b_FinalReturn;
    memcpy((void*)(&Mock.IsOverExit_b_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.IsOverExit_b_CallbackBool &&
      Mock.IsOverExit_b_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.IsOverExit_b_CallbackFunctionPointer(temp_mC, Mock.IsOverExit_b_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  {
    UNITY_SET_DETAILS(CMockString_IsOverExit_b,CMockString_temp_mC);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_temp_mC, temp_mC, cmock_line, CMockStringMismatch);
  }
  if (Mock.IsOverExit_b_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.IsOverExit_b_CallbackFunctionPointer(temp_mC, Mock.IsOverExit_b_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_IsOverExit_b(CMOCK_IsOverExit_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC);
void CMockExpectParameters_IsOverExit_b(CMOCK_IsOverExit_b_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC)
{
  cmock_call_instance->Expected_temp_mC = temp_mC;
}

void IsOverExit_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsOverExit_b_CALL_INSTANCE));
  CMOCK_IsOverExit_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsOverExit_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsOverExit_b_CallInstance = CMock_Guts_MemChain(Mock.IsOverExit_b_CallInstance, cmock_guts_index);
  Mock.IsOverExit_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.IsOverExit_b_IgnoreBool = (char)1;
}

void IsOverExit_b_CMockStopIgnore(void)
{
  if(Mock.IsOverExit_b_IgnoreBool)
    Mock.IsOverExit_b_CallInstance = CMock_Guts_MemNext(Mock.IsOverExit_b_CallInstance);
  Mock.IsOverExit_b_IgnoreBool = (char)0;
}

void IsOverExit_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int32_t temp_mC, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_IsOverExit_b_CALL_INSTANCE));
  CMOCK_IsOverExit_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_IsOverExit_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.IsOverExit_b_CallInstance = CMock_Guts_MemChain(Mock.IsOverExit_b_CallInstance, cmock_guts_index);
  Mock.IsOverExit_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  CMockExpectParameters_IsOverExit_b(cmock_call_instance, temp_mC);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void IsOverExit_b_AddCallback(CMOCK_IsOverExit_b_CALLBACK Callback)
{
  Mock.IsOverExit_b_IgnoreBool = (char)0;
  Mock.IsOverExit_b_CallbackBool = (char)1;
  Mock.IsOverExit_b_CallbackFunctionPointer = Callback;
}

void IsOverExit_b_Stub(CMOCK_IsOverExit_b_CALLBACK Callback)
{
  Mock.IsOverExit_b_IgnoreBool = (char)0;
  Mock.IsOverExit_b_CallbackBool = (char)0;
  Mock.IsOverExit_b_CallbackFunctionPointer = Callback;
}

