/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "TempMon_Run.h"
#include "unity.h"
#include "mock_TempMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_InitialStateIsNormal(void);
extern void test_NormalStateRemainsNormalWhenNoThresholdCrossed(void);
extern void test_NormalToUnderTransition(void);
extern void test_NormalToOverTransition(void);
extern void test_NormalPrioritizesUnderOverOver(void);
extern void test_UnderStateRemainsUnderWhenNoExit(void);
extern void test_UnderToNormalTransitionWithHysteresis(void);
extern void test_OverStateRemainsOverWhenNoExit(void);
extern void test_OverToNormalTransitionWithHysteresis(void);
extern void test_CompleteCycleNormalUnderNormal(void);
extern void test_CompleteCycleNormalOverNormal(void);
extern void test_MultipleTransitionsSequence(void);
extern void test_ConsecutiveCallsSameState(void);
extern void test_ExtremeLowTemperature(void);
extern void test_ExtremeHighTemperature(void);
extern void test_ZeroTemperatureInNormalState(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_TempMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_TempMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_TempMon_priv_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_TempMon_Run.c");
  run_test(test_InitialStateIsNormal, "test_InitialStateIsNormal", 18);
  run_test(test_NormalStateRemainsNormalWhenNoThresholdCrossed, "test_NormalStateRemainsNormalWhenNoThresholdCrossed", 25);
  run_test(test_NormalToUnderTransition, "test_NormalToUnderTransition", 38);
  run_test(test_NormalToOverTransition, "test_NormalToOverTransition", 50);
  run_test(test_NormalPrioritizesUnderOverOver, "test_NormalPrioritizesUnderOverOver", 64);
  run_test(test_UnderStateRemainsUnderWhenNoExit, "test_UnderStateRemainsUnderWhenNoExit", 78);
  run_test(test_UnderToNormalTransitionWithHysteresis, "test_UnderToNormalTransitionWithHysteresis", 93);
  run_test(test_OverStateRemainsOverWhenNoExit, "test_OverStateRemainsOverWhenNoExit", 110);
  run_test(test_OverToNormalTransitionWithHysteresis, "test_OverToNormalTransitionWithHysteresis", 125);
  run_test(test_CompleteCycleNormalUnderNormal, "test_CompleteCycleNormalUnderNormal", 142);
  run_test(test_CompleteCycleNormalOverNormal, "test_CompleteCycleNormalOverNormal", 162);
  run_test(test_MultipleTransitionsSequence, "test_MultipleTransitionsSequence", 184);
  run_test(test_ConsecutiveCallsSameState, "test_ConsecutiveCallsSameState", 212);
  run_test(test_ExtremeLowTemperature, "test_ExtremeLowTemperature", 237);
  run_test(test_ExtremeHighTemperature, "test_ExtremeHighTemperature", 249);
  run_test(test_ZeroTemperatureInNormalState, "test_ZeroTemperatureInNormalState", 262);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
