/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_TempMon.h"

static const char* CMockString_TempMon_GetSts = "TempMon_GetSts";
static const char* CMockString_TempMon_Init = "TempMon_Init";
static const char* CMockString_TempMon_IsOverAlv_b = "TempMon_IsOverAlv_b";
static const char* CMockString_TempMon_IsUnderAlv_b = "TempMon_IsUnderAlv_b";
static const char* CMockString_TempMon_Run = "TempMon_Run";
static const char* CMockString_temp_mC = "temp_mC";

typedef struct _CMOCK_TempMon_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  int32_t Expected_temp_mC;
  char IgnoreArg_temp_mC;

} CMOCK_TempMon_Init_CALL_INSTANCE;

typedef struct _CMOCK_TempMon_Run_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int CallOrder;
  int32_t Expected_temp_mC;
  char IgnoreArg_temp_mC;

} CMOCK_TempMon_Run_CALL_INSTANCE;

typedef struct _CMOCK_TempMon_GetSts_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  TempMon_sts_e ReturnVal;
  int CallOrder;

} CMOCK_TempMon_GetSts_CALL_INSTANCE;

typedef struct _CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  _Bool ReturnVal;
  int CallOrder;

} CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE;

typedef struct _CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  _Bool ReturnVal;
  int CallOrder;

} CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE;

static struct mock_TempMonInstance
{
  char TempMon_Init_IgnoreBool;
  char TempMon_Init_CallbackBool;
  CMOCK_TempMon_Init_CALLBACK TempMon_Init_CallbackFunctionPointer;
  int TempMon_Init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TempMon_Init_CallInstance;
  char TempMon_Run_IgnoreBool;
  char TempMon_Run_CallbackBool;
  CMOCK_TempMon_Run_CALLBACK TempMon_Run_CallbackFunctionPointer;
  int TempMon_Run_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TempMon_Run_CallInstance;
  char TempMon_GetSts_IgnoreBool;
  TempMon_sts_e TempMon_GetSts_FinalReturn;
  char TempMon_GetSts_CallbackBool;
  CMOCK_TempMon_GetSts_CALLBACK TempMon_GetSts_CallbackFunctionPointer;
  int TempMon_GetSts_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TempMon_GetSts_CallInstance;
  char TempMon_IsUnderAlv_b_IgnoreBool;
  _Bool TempMon_IsUnderAlv_b_FinalReturn;
  char TempMon_IsUnderAlv_b_CallbackBool;
  CMOCK_TempMon_IsUnderAlv_b_CALLBACK TempMon_IsUnderAlv_b_CallbackFunctionPointer;
  int TempMon_IsUnderAlv_b_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TempMon_IsUnderAlv_b_CallInstance;
  char TempMon_IsOverAlv_b_IgnoreBool;
  _Bool TempMon_IsOverAlv_b_FinalReturn;
  char TempMon_IsOverAlv_b_CallbackBool;
  CMOCK_TempMon_IsOverAlv_b_CALLBACK TempMon_IsOverAlv_b_CallbackFunctionPointer;
  int TempMon_IsOverAlv_b_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE TempMon_IsOverAlv_b_CallInstance;
} Mock;

extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_TempMon_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.TempMon_Init_CallInstance;
  if (Mock.TempMon_Init_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TempMon_Init);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TempMon_Init_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TempMon_Run_CallInstance;
  if (Mock.TempMon_Run_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TempMon_Run);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TempMon_Run_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TempMon_GetSts_CallInstance;
  if (Mock.TempMon_GetSts_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TempMon_GetSts);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TempMon_GetSts_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TempMon_IsUnderAlv_b_CallInstance;
  if (Mock.TempMon_IsUnderAlv_b_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TempMon_IsUnderAlv_b);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.TempMon_IsOverAlv_b_CallInstance;
  if (Mock.TempMon_IsOverAlv_b_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_TempMon_IsOverAlv_b);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_TempMon_Init(void)
{
  mock_TempMon_Destroy();
}

void mock_TempMon_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

void TempMon_Init(int32_t temp_mC)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TempMon_Init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TempMon_Init);
  cmock_call_instance = (CMOCK_TempMon_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TempMon_Init_CallInstance);
  Mock.TempMon_Init_CallInstance = CMock_Guts_MemNext(Mock.TempMon_Init_CallInstance);
  if (Mock.TempMon_Init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.TempMon_Init_CallbackBool &&
      Mock.TempMon_Init_CallbackFunctionPointer != NULL)
  {
    Mock.TempMon_Init_CallbackFunctionPointer(temp_mC, Mock.TempMon_Init_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_temp_mC)
  {
    UNITY_SET_DETAILS(CMockString_TempMon_Init,CMockString_temp_mC);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_temp_mC, temp_mC, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.TempMon_Init_CallbackFunctionPointer != NULL)
  {
    Mock.TempMon_Init_CallbackFunctionPointer(temp_mC, Mock.TempMon_Init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_TempMon_Init(CMOCK_TempMon_Init_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC);
void CMockExpectParameters_TempMon_Init(CMOCK_TempMon_Init_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC)
{
  cmock_call_instance->Expected_temp_mC = temp_mC;
  cmock_call_instance->IgnoreArg_temp_mC = 0;
}

void TempMon_Init_CMockIgnore(void)
{
  Mock.TempMon_Init_IgnoreBool = (char)1;
}

void TempMon_Init_CMockStopIgnore(void)
{
  Mock.TempMon_Init_IgnoreBool = (char)0;
}

void TempMon_Init_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_Init_CALL_INSTANCE));
  CMOCK_TempMon_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_Init_CallInstance = CMock_Guts_MemChain(Mock.TempMon_Init_CallInstance, cmock_guts_index);
  Mock.TempMon_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void TempMon_Init_CMockExpect(UNITY_LINE_TYPE cmock_line, int32_t temp_mC)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_Init_CALL_INSTANCE));
  CMOCK_TempMon_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_Init_CallInstance = CMock_Guts_MemChain(Mock.TempMon_Init_CallInstance, cmock_guts_index);
  Mock.TempMon_Init_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_TempMon_Init(cmock_call_instance, temp_mC);
}

void TempMon_Init_AddCallback(CMOCK_TempMon_Init_CALLBACK Callback)
{
  Mock.TempMon_Init_IgnoreBool = (char)0;
  Mock.TempMon_Init_CallbackBool = (char)1;
  Mock.TempMon_Init_CallbackFunctionPointer = Callback;
}

void TempMon_Init_Stub(CMOCK_TempMon_Init_CALLBACK Callback)
{
  Mock.TempMon_Init_IgnoreBool = (char)0;
  Mock.TempMon_Init_CallbackBool = (char)0;
  Mock.TempMon_Init_CallbackFunctionPointer = Callback;
}

void TempMon_Init_CMockIgnoreArg_temp_mC(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TempMon_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TempMon_Init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_temp_mC = 1;
}

void TempMon_Run(int32_t temp_mC)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TempMon_Run_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TempMon_Run);
  cmock_call_instance = (CMOCK_TempMon_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TempMon_Run_CallInstance);
  Mock.TempMon_Run_CallInstance = CMock_Guts_MemNext(Mock.TempMon_Run_CallInstance);
  if (Mock.TempMon_Run_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.TempMon_Run_CallbackBool &&
      Mock.TempMon_Run_CallbackFunctionPointer != NULL)
  {
    Mock.TempMon_Run_CallbackFunctionPointer(temp_mC, Mock.TempMon_Run_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_temp_mC)
  {
    UNITY_SET_DETAILS(CMockString_TempMon_Run,CMockString_temp_mC);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_temp_mC, temp_mC, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.TempMon_Run_CallbackFunctionPointer != NULL)
  {
    Mock.TempMon_Run_CallbackFunctionPointer(temp_mC, Mock.TempMon_Run_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_TempMon_Run(CMOCK_TempMon_Run_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC);
void CMockExpectParameters_TempMon_Run(CMOCK_TempMon_Run_CALL_INSTANCE* cmock_call_instance, int32_t temp_mC)
{
  cmock_call_instance->Expected_temp_mC = temp_mC;
  cmock_call_instance->IgnoreArg_temp_mC = 0;
}

void TempMon_Run_CMockIgnore(void)
{
  Mock.TempMon_Run_IgnoreBool = (char)1;
}

void TempMon_Run_CMockStopIgnore(void)
{
  Mock.TempMon_Run_IgnoreBool = (char)0;
}

void TempMon_Run_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_Run_CALL_INSTANCE));
  CMOCK_TempMon_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_Run_CallInstance = CMock_Guts_MemChain(Mock.TempMon_Run_CallInstance, cmock_guts_index);
  Mock.TempMon_Run_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void TempMon_Run_CMockExpect(UNITY_LINE_TYPE cmock_line, int32_t temp_mC)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_Run_CALL_INSTANCE));
  CMOCK_TempMon_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_Run_CallInstance = CMock_Guts_MemChain(Mock.TempMon_Run_CallInstance, cmock_guts_index);
  Mock.TempMon_Run_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_TempMon_Run(cmock_call_instance, temp_mC);
}

void TempMon_Run_AddCallback(CMOCK_TempMon_Run_CALLBACK Callback)
{
  Mock.TempMon_Run_IgnoreBool = (char)0;
  Mock.TempMon_Run_CallbackBool = (char)1;
  Mock.TempMon_Run_CallbackFunctionPointer = Callback;
}

void TempMon_Run_Stub(CMOCK_TempMon_Run_CALLBACK Callback)
{
  Mock.TempMon_Run_IgnoreBool = (char)0;
  Mock.TempMon_Run_CallbackBool = (char)0;
  Mock.TempMon_Run_CallbackFunctionPointer = Callback;
}

void TempMon_Run_CMockIgnoreArg_temp_mC(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_TempMon_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.TempMon_Run_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_temp_mC = 1;
}

TempMon_sts_e TempMon_GetSts(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TempMon_GetSts_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TempMon_GetSts);
  cmock_call_instance = (CMOCK_TempMon_GetSts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TempMon_GetSts_CallInstance);
  Mock.TempMon_GetSts_CallInstance = CMock_Guts_MemNext(Mock.TempMon_GetSts_CallInstance);
  if (Mock.TempMon_GetSts_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TempMon_GetSts_FinalReturn;
    memcpy((void*)(&Mock.TempMon_GetSts_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(TempMon_sts_e[sizeof(cmock_call_instance->ReturnVal) == sizeof(TempMon_sts_e) ? 1 : -1])); /* add TempMon_sts_e to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.TempMon_GetSts_CallbackBool &&
      Mock.TempMon_GetSts_CallbackFunctionPointer != NULL)
  {
    TempMon_sts_e cmock_cb_ret = Mock.TempMon_GetSts_CallbackFunctionPointer(Mock.TempMon_GetSts_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.TempMon_GetSts_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.TempMon_GetSts_CallbackFunctionPointer(Mock.TempMon_GetSts_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void TempMon_GetSts_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, TempMon_sts_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_GetSts_CALL_INSTANCE));
  CMOCK_TempMon_GetSts_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_GetSts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_GetSts_CallInstance = CMock_Guts_MemChain(Mock.TempMon_GetSts_CallInstance, cmock_guts_index);
  Mock.TempMon_GetSts_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TempMon_GetSts_IgnoreBool = (char)1;
}

void TempMon_GetSts_CMockStopIgnore(void)
{
  if(Mock.TempMon_GetSts_IgnoreBool)
    Mock.TempMon_GetSts_CallInstance = CMock_Guts_MemNext(Mock.TempMon_GetSts_CallInstance);
  Mock.TempMon_GetSts_IgnoreBool = (char)0;
}

void TempMon_GetSts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TempMon_sts_e cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_GetSts_CALL_INSTANCE));
  CMOCK_TempMon_GetSts_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_GetSts_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_GetSts_CallInstance = CMock_Guts_MemChain(Mock.TempMon_GetSts_CallInstance, cmock_guts_index);
  Mock.TempMon_GetSts_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(TempMon_sts_e[sizeof(cmock_to_return) == sizeof(TempMon_sts_e) ? 1 : -1])); /* add TempMon_sts_e to :treat_as_array if this causes an error */
}

void TempMon_GetSts_AddCallback(CMOCK_TempMon_GetSts_CALLBACK Callback)
{
  Mock.TempMon_GetSts_IgnoreBool = (char)0;
  Mock.TempMon_GetSts_CallbackBool = (char)1;
  Mock.TempMon_GetSts_CallbackFunctionPointer = Callback;
}

void TempMon_GetSts_Stub(CMOCK_TempMon_GetSts_CALLBACK Callback)
{
  Mock.TempMon_GetSts_IgnoreBool = (char)0;
  Mock.TempMon_GetSts_CallbackBool = (char)0;
  Mock.TempMon_GetSts_CallbackFunctionPointer = Callback;
}

_Bool TempMon_IsUnderAlv_b(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TempMon_IsUnderAlv_b);
  cmock_call_instance = (CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TempMon_IsUnderAlv_b_CallInstance);
  Mock.TempMon_IsUnderAlv_b_CallInstance = CMock_Guts_MemNext(Mock.TempMon_IsUnderAlv_b_CallInstance);
  if (Mock.TempMon_IsUnderAlv_b_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TempMon_IsUnderAlv_b_FinalReturn;
    memcpy((void*)(&Mock.TempMon_IsUnderAlv_b_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.TempMon_IsUnderAlv_b_CallbackBool &&
      Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer(Mock.TempMon_IsUnderAlv_b_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer(Mock.TempMon_IsUnderAlv_b_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void TempMon_IsUnderAlv_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE));
  CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_IsUnderAlv_b_CallInstance = CMock_Guts_MemChain(Mock.TempMon_IsUnderAlv_b_CallInstance, cmock_guts_index);
  Mock.TempMon_IsUnderAlv_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TempMon_IsUnderAlv_b_IgnoreBool = (char)1;
}

void TempMon_IsUnderAlv_b_CMockStopIgnore(void)
{
  if(Mock.TempMon_IsUnderAlv_b_IgnoreBool)
    Mock.TempMon_IsUnderAlv_b_CallInstance = CMock_Guts_MemNext(Mock.TempMon_IsUnderAlv_b_CallInstance);
  Mock.TempMon_IsUnderAlv_b_IgnoreBool = (char)0;
}

void TempMon_IsUnderAlv_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE));
  CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_IsUnderAlv_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_IsUnderAlv_b_CallInstance = CMock_Guts_MemChain(Mock.TempMon_IsUnderAlv_b_CallInstance, cmock_guts_index);
  Mock.TempMon_IsUnderAlv_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void TempMon_IsUnderAlv_b_AddCallback(CMOCK_TempMon_IsUnderAlv_b_CALLBACK Callback)
{
  Mock.TempMon_IsUnderAlv_b_IgnoreBool = (char)0;
  Mock.TempMon_IsUnderAlv_b_CallbackBool = (char)1;
  Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer = Callback;
}

void TempMon_IsUnderAlv_b_Stub(CMOCK_TempMon_IsUnderAlv_b_CALLBACK Callback)
{
  Mock.TempMon_IsUnderAlv_b_IgnoreBool = (char)0;
  Mock.TempMon_IsUnderAlv_b_CallbackBool = (char)0;
  Mock.TempMon_IsUnderAlv_b_CallbackFunctionPointer = Callback;
}

_Bool TempMon_IsOverAlv_b(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_TempMon_IsOverAlv_b);
  cmock_call_instance = (CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TempMon_IsOverAlv_b_CallInstance);
  Mock.TempMon_IsOverAlv_b_CallInstance = CMock_Guts_MemNext(Mock.TempMon_IsOverAlv_b_CallInstance);
  if (Mock.TempMon_IsOverAlv_b_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.TempMon_IsOverAlv_b_FinalReturn;
    memcpy((void*)(&Mock.TempMon_IsOverAlv_b_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(_Bool[sizeof(cmock_call_instance->ReturnVal) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.TempMon_IsOverAlv_b_CallbackBool &&
      Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer != NULL)
  {
    _Bool cmock_cb_ret = Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer(Mock.TempMon_IsOverAlv_b_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer(Mock.TempMon_IsOverAlv_b_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void TempMon_IsOverAlv_b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE));
  CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_IsOverAlv_b_CallInstance = CMock_Guts_MemChain(Mock.TempMon_IsOverAlv_b_CallInstance, cmock_guts_index);
  Mock.TempMon_IsOverAlv_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.TempMon_IsOverAlv_b_IgnoreBool = (char)1;
}

void TempMon_IsOverAlv_b_CMockStopIgnore(void)
{
  if(Mock.TempMon_IsOverAlv_b_IgnoreBool)
    Mock.TempMon_IsOverAlv_b_CallInstance = CMock_Guts_MemNext(Mock.TempMon_IsOverAlv_b_CallInstance);
  Mock.TempMon_IsOverAlv_b_IgnoreBool = (char)0;
}

void TempMon_IsOverAlv_b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, _Bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE));
  CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE* cmock_call_instance = (CMOCK_TempMon_IsOverAlv_b_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.TempMon_IsOverAlv_b_CallInstance = CMock_Guts_MemChain(Mock.TempMon_IsOverAlv_b_CallInstance, cmock_guts_index);
  Mock.TempMon_IsOverAlv_b_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(_Bool[sizeof(cmock_to_return) == sizeof(_Bool) ? 1 : -1])); /* add _Bool to :treat_as_array if this causes an error */
}

void TempMon_IsOverAlv_b_AddCallback(CMOCK_TempMon_IsOverAlv_b_CALLBACK Callback)
{
  Mock.TempMon_IsOverAlv_b_IgnoreBool = (char)0;
  Mock.TempMon_IsOverAlv_b_CallbackBool = (char)1;
  Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer = Callback;
}

void TempMon_IsOverAlv_b_Stub(CMOCK_TempMon_IsOverAlv_b_CALLBACK Callback)
{
  Mock.TempMon_IsOverAlv_b_IgnoreBool = (char)0;
  Mock.TempMon_IsOverAlv_b_CallbackBool = (char)0;
  Mock.TempMon_IsOverAlv_b_CallbackFunctionPointer = Callback;
}

