/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "TempMon.h"
#include "TempMon_Run.h"
#include "unity.h"
#include "mock_TempMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_Hysteresis_value_of_zero_allows_immediate_recovery_from_UNDER_when_temperature_equals_under_threshold(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_TempMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_TempMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_TempMon_priv_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_Hysteresis_value_of_zero_allows_immediate_recovery_from_UNDER_when_temperature_equals_under_threshold.c");
  run_test(test_Hysteresis_value_of_zero_allows_immediate_recovery_from_UNDER_when_temperature_equals_under_threshold, "test_Hysteresis_value_of_zero_allows_immediate_recovery_from_UNDER_when_temperature_equals_under_threshold", 23);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
