/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "TempMon.h"
#include "TempMon_Run.h"
#include "unity.h"
#include "mock_TempMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_NORMAL_state_remains_NORMAL_when_temp_in_range(void);
extern void test_NORMAL_to_UNDER_transition(void);
extern void test_NORMAL_to_OVER_transition(void);
extern void test_NORMAL_state_at_under_threshold_boundary(void);
extern void test_NORMAL_state_at_over_threshold_boundary(void);
extern void test_UNDER_state_remains_UNDER_when_temp_below_hysteresis(void);
extern void test_UNDER_to_NORMAL_transition_with_hysteresis(void);
extern void test_UNDER_state_at_hysteresis_boundary(void);
extern void test_UNDER_state_just_above_hysteresis_boundary(void);
extern void test_OVER_state_remains_OVER_when_temp_above_hysteresis(void);
extern void test_OVER_to_NORMAL_transition_with_hysteresis(void);
extern void test_OVER_state_at_hysteresis_boundary(void);
extern void test_OVER_state_just_below_hysteresis_boundary(void);
extern void test_cycle_NORMAL_to_UNDER_back_to_NORMAL(void);
extern void test_cycle_NORMAL_to_OVER_back_to_NORMAL(void);
extern void test_zero_hysteresis_UNDER_to_NORMAL(void);
extern void test_zero_hysteresis_OVER_to_NORMAL(void);
extern void test_large_hysteresis_UNDER_to_NORMAL(void);
extern void test_negative_temperatures(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_TempMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_TempMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_TempMon_priv_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_TempMon_Run.c");
  run_test(test_NORMAL_state_remains_NORMAL_when_temp_in_range, "test_NORMAL_state_remains_NORMAL_when_temp_in_range", 36);
  run_test(test_NORMAL_to_UNDER_transition, "test_NORMAL_to_UNDER_transition", 52);
  run_test(test_NORMAL_to_OVER_transition, "test_NORMAL_to_OVER_transition", 68);
  run_test(test_NORMAL_state_at_under_threshold_boundary, "test_NORMAL_state_at_under_threshold_boundary", 84);
  run_test(test_NORMAL_state_at_over_threshold_boundary, "test_NORMAL_state_at_over_threshold_boundary", 100);
  run_test(test_UNDER_state_remains_UNDER_when_temp_below_hysteresis, "test_UNDER_state_remains_UNDER_when_temp_below_hysteresis", 118);
  run_test(test_UNDER_to_NORMAL_transition_with_hysteresis, "test_UNDER_to_NORMAL_transition_with_hysteresis", 134);
  run_test(test_UNDER_state_at_hysteresis_boundary, "test_UNDER_state_at_hysteresis_boundary", 150);
  run_test(test_UNDER_state_just_above_hysteresis_boundary, "test_UNDER_state_just_above_hysteresis_boundary", 167);
  run_test(test_OVER_state_remains_OVER_when_temp_above_hysteresis, "test_OVER_state_remains_OVER_when_temp_above_hysteresis", 185);
  run_test(test_OVER_to_NORMAL_transition_with_hysteresis, "test_OVER_to_NORMAL_transition_with_hysteresis", 201);
  run_test(test_OVER_state_at_hysteresis_boundary, "test_OVER_state_at_hysteresis_boundary", 217);
  run_test(test_OVER_state_just_below_hysteresis_boundary, "test_OVER_state_just_below_hysteresis_boundary", 234);
  run_test(test_cycle_NORMAL_to_UNDER_back_to_NORMAL, "test_cycle_NORMAL_to_UNDER_back_to_NORMAL", 252);
  run_test(test_cycle_NORMAL_to_OVER_back_to_NORMAL, "test_cycle_NORMAL_to_OVER_back_to_NORMAL", 271);
  run_test(test_zero_hysteresis_UNDER_to_NORMAL, "test_zero_hysteresis_UNDER_to_NORMAL", 290);
  run_test(test_zero_hysteresis_OVER_to_NORMAL, "test_zero_hysteresis_OVER_to_NORMAL", 306);
  run_test(test_large_hysteresis_UNDER_to_NORMAL, "test_large_hysteresis_UNDER_to_NORMAL", 322);
  run_test(test_negative_temperatures, "test_negative_temperatures", 340);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
