/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "TempMon.h"
#include "TempMon_Run.h"
#include "unity.h"
#include "mock_TempMon_priv.h"

int GlobalExpectCount;
int GlobalVerifyOrder;
char* GlobalOrderError;

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_TempMon_Run_transitions_from_NORMAL_to_UNDER_when_temp_just_below_UnderThreshold(void);
extern void test_TempMon_Run_stays_in_NORMAL_when_temp_exactly_at_UnderThreshold(void);
extern void test_TempMon_Run_stays_in_NORMAL_when_temp_just_above_UnderThreshold_below_OverThreshold(void);
extern void test_TempMon_Run_transitions_from_NORMAL_to_OVER_when_temp_just_above_OverThreshold(void);
extern void test_TempMon_Run_stays_in_NORMAL_when_temp_exactly_at_OverThreshold(void);
extern void test_TempMon_Run_stays_in_NORMAL_when_temp_just_below_OverThreshold_above_UnderThreshold(void);
extern void test_TempMon_Run_transitions_from_UNDER_to_NORMAL_when_temp_just_above_UnderThreshold_plus_Hyst(void);
extern void test_TempMon_Run_stays_in_UNDER_when_temp_exactly_at_UnderThreshold_plus_Hyst(void);
extern void test_TempMon_Run_stays_in_UNDER_when_temp_just_below_UnderThreshold_plus_Hyst(void);
extern void test_TempMon_Run_transitions_from_OVER_to_NORMAL_when_temp_just_below_OverThreshold_minus_Hyst(void);
extern void test_TempMon_Run_stays_in_OVER_when_temp_exactly_at_OverThreshold_minus_Hyst(void);
extern void test_TempMon_Run_stays_in_OVER_when_temp_just_above_OverThreshold_minus_Hyst(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
  GlobalOrderError = NULL;
  mock_TempMon_priv_Init();
}
static void CMock_Verify(void)
{
  mock_TempMon_priv_Verify();
}
static void CMock_Destroy(void)
{
  mock_TempMon_priv_Destroy();
}

/*=======Teardown (stub)=====*/
void tearDown(void) {}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test_TempMon_Run.c");
  run_test(test_TempMon_Run_transitions_from_NORMAL_to_UNDER_when_temp_just_below_UnderThreshold, "test_TempMon_Run_transitions_from_NORMAL_to_UNDER_when_temp_just_below_UnderThreshold", 16);
  run_test(test_TempMon_Run_stays_in_NORMAL_when_temp_exactly_at_UnderThreshold, "test_TempMon_Run_stays_in_NORMAL_when_temp_exactly_at_UnderThreshold", 28);
  run_test(test_TempMon_Run_stays_in_NORMAL_when_temp_just_above_UnderThreshold_below_OverThreshold, "test_TempMon_Run_stays_in_NORMAL_when_temp_just_above_UnderThreshold_below_OverThreshold", 40);
  run_test(test_TempMon_Run_transitions_from_NORMAL_to_OVER_when_temp_just_above_OverThreshold, "test_TempMon_Run_transitions_from_NORMAL_to_OVER_when_temp_just_above_OverThreshold", 52);
  run_test(test_TempMon_Run_stays_in_NORMAL_when_temp_exactly_at_OverThreshold, "test_TempMon_Run_stays_in_NORMAL_when_temp_exactly_at_OverThreshold", 64);
  run_test(test_TempMon_Run_stays_in_NORMAL_when_temp_just_below_OverThreshold_above_UnderThreshold, "test_TempMon_Run_stays_in_NORMAL_when_temp_just_below_OverThreshold_above_UnderThreshold", 76);
  run_test(test_TempMon_Run_transitions_from_UNDER_to_NORMAL_when_temp_just_above_UnderThreshold_plus_Hyst, "test_TempMon_Run_transitions_from_UNDER_to_NORMAL_when_temp_just_above_UnderThreshold_plus_Hyst", 88);
  run_test(test_TempMon_Run_stays_in_UNDER_when_temp_exactly_at_UnderThreshold_plus_Hyst, "test_TempMon_Run_stays_in_UNDER_when_temp_exactly_at_UnderThreshold_plus_Hyst", 100);
  run_test(test_TempMon_Run_stays_in_UNDER_when_temp_just_below_UnderThreshold_plus_Hyst, "test_TempMon_Run_stays_in_UNDER_when_temp_just_below_UnderThreshold_plus_Hyst", 112);
  run_test(test_TempMon_Run_transitions_from_OVER_to_NORMAL_when_temp_just_below_OverThreshold_minus_Hyst, "test_TempMon_Run_transitions_from_OVER_to_NORMAL_when_temp_just_below_OverThreshold_minus_Hyst", 124);
  run_test(test_TempMon_Run_stays_in_OVER_when_temp_exactly_at_OverThreshold_minus_Hyst, "test_TempMon_Run_stays_in_OVER_when_temp_exactly_at_OverThreshold_minus_Hyst", 136);
  run_test(test_TempMon_Run_stays_in_OVER_when_temp_just_above_OverThreshold_minus_Hyst, "test_TempMon_Run_stays_in_OVER_when_temp_just_above_OverThreshold_minus_Hyst", 148);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
